### ISSUE TITLE
Accessing matched fromTopic name segment in toTopic

### ISSUE THREAD

**Issue by ginkel** [tg44/mqtt-transformer#8]
Hello again,

let's say, I have multiple MQTT topics that contain scalar values that I'd like to map to JSON and re-publish on distinct topics.

How would I achieve this without having to define a transform per source topic?

ATM I do have the following config snippet (imagine this being JSON, the YAML will automatically be transformed during deployment):

```
  transforms:
    - fromTopic: zigbee2mqtt/+/availability
      toTopic: zigbee_availability
      emitType: map
      wrapper: availability
      template:
        availability:
          $eval: availability
```

Is there a way to access the topic name fragment matched by the `+` from the `toTopic`?

Thanks,
Thilo
